# Generated by Django 2.2.3 on 2019-07-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=250, verbose_name='Texto da Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Pessoa')),
                ('datanascimento', models.DateTimeField()),
                ('nacionalidade', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Artesanato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Tipo de Artesanato')),
                ('artesao', models.ManyToManyField(to='artesanatomain.Artesao')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Técnica')),
                ('artesao', models.ManyToManyField(to='artesanatomain.Artesao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=250, verbose_name='Texto da Resposta')),
                ('pergunta', models.ManyToManyField(to='artesanatomain.Pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipoartesanato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artesanatomain.Tipo_Artesanato'),
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=5000, verbose_name='História')),
                ('artesao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artesanatomain.Artesao')),
            ],
        ),
        migrations.AddField(
            model_name='artesao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artesanatomain.Pessoa'),
        ),
    ]
