# Generated by Django 2.2.3 on 2019-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanatomain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnica',
            name='descricao',
            field=models.CharField(default='teste', max_length=5000, verbose_name='Sobre a Técnica'),
            preserve_default=False,
        ),
    ]
